pipeline {
    agent any
    options {
        timeout(time: 2, unit: 'HOURS')
    }
    stages  {
        stage('Package') {
            steps {
                sh 'yarn install'
                sh 'yarn build:demo'
            }
        }
        stage('Deliver for demo') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'USER.FRUITS', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh "bash scripts/deploy/deploy.sh dev-001 ${username} ${password} peach-admin-web_demo"
                }
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: '*.tar.bz2', fingerprint: true
            sh 'rm *.tar.bz2'
        }
    }
}
